### ISSUE TITLE
🧪 Tooling: Ensure that all exported functions have a code example

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#52]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

In #5, I filled out a bunch of docs in the `README.md`: one section for each exported function. But there's nothing enforcing that subsequent PRs don't add more functions without documenting them similarly.

Let's add some kind of unit test that:

* Imports `ts-api-utils`
* Reads in the `README.md`
* Ensures that each export from `ts-api-utils` exists in the `README.md`

**Comment by RebeccaStevens** [comment]
Due to the share number of functions exported by this library, I think it would be better to put all these docs in an `API.md` file rather than cluttering up the readme. The readme can then link to that file. Each of the categories within the API docs could even be split up into sub-files to prevent the API file from becoming huge.

Having a huge readme file can be a bit daunting for new users when they first look at it.

**Comment by JoshuaKGoldberg** [comment]
Agreed! Filed #56. We can consider this issue to be about the docs in whatever file(s) contain them.

**Comment by JoshuaKGoldberg** [comment]
I do like the idea behind this though - making sure everything has docs. Reworded slightly. WDYT?

**Comment by RebeccaStevens** [comment]
I've made a new (WIP) plugin for typedoc to require tags to exists. We can use this to require `@example` tags exists on all function.

https://github.com/RebeccaStevens/typedoc-plugin-require-tags/pull/1
